// ─── Promotion and revert: the only path from a measurement to a change ───
//
// A promotion writes the variant's lines into `~/.gear/config.toml` inside a
// generated fenced block — the same marker discipline the playbook uses, for
// the same reason: everything a person wrote outside the markers is kept, and
// the machine's contribution is visible, diffable and removable by hand.
//
// Everything a promotion must refuse is here, and each refusal has a failure it
// is named after:
//
//   · no passing measurement for THIS EXACT arm pair — the evidence has to be
//     about the change being made, not about a change that shared its name;
//   · the yardstick moved since a human blessed it — a loop that can edit the
//     eval suite and then promote on the result is grading its own exam;
//   · a promotion already happened inside the interval — one change at a time,
//     or the next measurement cannot attribute anything;
//   · two consecutive reverts — a loop promoting changes a human keeps undoing
//     has a broken fitness function, and the answer is to stop.
//
// Revert is the counterpart and it is one command with no arguments, because a
// revert you have to think about is a revert that does not happen.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { getGearHome } from "@gear/shared";

import { configHash } from "./config-hash";
import {
  activePromotions,
  appendLedger,
  haltState,
  lastPromotion,
  passingMeasurement,
  readLedger,
  type LedgerEntry,
} from "./ledger";
import { isVariantId, variantConfig, variantConfigLines, type VariantId } from "./variants";

export const CONFIG_FILE = "config.toml";
const START = "# <<< gear:evolve:start — generated by `gear evolve promote`; edit above this line";
const END = "# >>> gear:evolve:end";

/** One promotion per this many ms. Overridable for tests, not for the loop. */
export const PROMOTE_INTERVAL_MS = 24 * 60 * 60 * 1000;

export interface PromoteEnv {
  /** GEAR_HOME to act on. Defaults to the real one. */
  home?: string;
  /** Yardstick digest of the checkout being promoted from. */
  yardstick?: string | null;
  /** The digest a human last blessed. Null = never blessed. */
  blessedYardstick?: string | null;
  now?: Date;
  intervalMs?: number;
}

export interface PromoteResult {
  ok: boolean;
  /** Why it refused, in the user's words. Empty on success. */
  refusals: string[];
  configPath?: string;
  configLines?: string[];
  measurement?: LedgerEntry;
}

export function configPath(home: string = getGearHome()): string {
  return join(home, CONFIG_FILE);
}

/** The generated block for a set of active promotions, markers included. */
export function renderConfigBlock(promotions: LedgerEntry[]): string {
  const lines: string[] = [START];
  if (promotions.length === 0) return "";
  lines.push(
    `# ${promotions.length} promotion${promotions.length === 1 ? "" : "s"} from measured A/B wins. \`gear evolve revert\` removes the newest;`,
    "# `gear evolve why <variant>` prints the evidence. Anything you write ABOVE the",
    "# start marker is kept untouched; settings here win, because they come last.",
  );
  // Oldest first, so the newest promotion's values land last and win.
  for (const p of [...promotions].reverse()) {
    lines.push("", `# ${p.subject} · promoted ${p.at.slice(0, 10)} · ${p.treatmentConfigHash}`);
    lines.push(...(p.configLines ?? []));
  }
  lines.push(END);
  return lines.join("\n");
}

/**
 * Splice the generated block into a config file, always at the END.
 *
 * The parser this config feeds re-enters a repeated `[section]` and lets later
 * keys win, so a block at the end is exactly "these settings override what is
 * above". Relocating it on every write keeps that true.
 */
export function spliceConfigBlock(current: string, block: string): string {
  const s = current.indexOf(START);
  const e = current.indexOf(END);
  let base = current;
  if (s !== -1 && e !== -1 && e > s) {
    base = current.slice(0, s) + current.slice(e + END.length);
  }
  base = base.replace(/\n{3,}$/, "\n").replace(/\s*$/, "");
  if (!block) return base ? `${base}\n` : "";
  return base ? `${base}\n\n${block}\n` : `${block}\n`;
}

function writeConfig(home: string, promotions: LedgerEntry[]): string {
  const path = configPath(home);
  mkdirSync(dirname(path), { recursive: true });
  const current = existsSync(path) ? readFileSync(path, "utf8") : "";
  writeFileSync(path, spliceConfigBlock(current, renderConfigBlock(promotions)));
  return path;
}

export function promote(variant: string, env: PromoteEnv = {}): PromoteResult {
  const home = env.home ?? getGearHome();
  const now = env.now ?? new Date();
  const intervalMs = env.intervalMs ?? PROMOTE_INTERVAL_MS;
  const refusals: string[] = [];

  if (!isVariantId(variant)) {
    return {
      ok: false,
      refusals: [
        `"${variant}" is not a declared variant. The registry is closed on purpose (packages/orchestrator/src/evolve/variants.ts).`,
      ],
    };
  }
  const id = variant as VariantId;
  const entries = readLedger(home);

  const halt = haltState(entries);
  if (halt.halted) {
    refusals.push(`the loop is halted: ${halt.reason}. Clear it with \`gear evolve resume\`.`);
  }

  const pair = { control: configHash({}), treatment: configHash(variantConfig(id)) };
  const measurement = passingMeasurement(entries, id, pair);
  if (!measurement) {
    refusals.push(
      `no passing A/B in the ledger for ${id} at this exact configuration (control ${pair.control} → treatment ${pair.treatment}). Run \`gear evolve ab ${id}\` first; a measurement of an older shape of this variant is evidence about a different change.`,
    );
  }

  if (env.yardstick !== undefined && env.blessedYardstick !== undefined) {
    if (env.yardstick && env.blessedYardstick && env.yardstick !== env.blessedYardstick) {
      refusals.push(
        `the yardstick moved: tests/eval/** is at ${env.yardstick}, last blessed at ${env.blessedYardstick}. A loop that edits the eval suite and then promotes on the result is grading its own exam — re-baseline with \`gear evolve yardstick --bless\`.`,
      );
    } else if (env.yardstick && !env.blessedYardstick) {
      refusals.push(
        `the yardstick at ${env.yardstick} has never been blessed. Run \`gear evolve yardstick --bless\` once to anchor it.`,
      );
    }
  }

  const previous = lastPromotion(entries);
  if (previous) {
    const elapsed = now.getTime() - new Date(previous.at).getTime();
    if (elapsed < intervalMs) {
      const hours = Math.ceil((intervalMs - elapsed) / 3_600_000);
      refusals.push(
        `${previous.subject} was promoted ${Math.round(elapsed / 3_600_000)}h ago; one promotion per ${Math.round(intervalMs / 3_600_000)}h. Two changes at once cannot be attributed. Wait ${hours}h.`,
      );
    }
  }

  const already = activePromotions(entries).find((p) => p.subject === id);
  if (already) {
    refusals.push(`${id} is already promoted (${already.at.slice(0, 10)}); nothing to do.`);
  }

  const configLines = variantConfigLines(id);
  if (configLines.length === 0) {
    refusals.push(
      `${id} renders no config lines, so promoting it would write nothing — that is a registry bug, not a no-op.`,
    );
  }

  if (refusals.length > 0) return { ok: false, refusals };

  const entry: LedgerEntry = {
    v: 1,
    at: now.toISOString(),
    kind: "promotion",
    subject: id,
    controlConfigHash: pair.control,
    treatmentConfigHash: pair.treatment,
    doctrineHash: measurement!.doctrineHash ?? null,
    yardstick: env.yardstick ?? measurement!.yardstick ?? null,
    mode: measurement!.mode,
    rateDelta: measurement!.rateDelta,
    costDelta: measurement!.costDelta,
    compared: measurement!.compared,
    configLines,
  };
  appendLedger(entry, home);
  const path = writeConfig(home, activePromotions(readLedger(home)));
  return { ok: true, refusals: [], configPath: path, configLines, measurement: measurement! };
}

export interface RevertResult {
  ok: boolean;
  reverted: string[];
  refusals: string[];
  configPath?: string;
  /** True when this revert tripped the two-consecutive-reverts halt. */
  halted: boolean;
  haltReason?: string;
}

/**
 * Undo the newest `n` promotions. Records a revert row for each — never a
 * deletion, because "why does it believe this" has to survive the belief being
 * wrong — then rewrites the config block from whatever is left standing.
 */
export function revert(n = 1, env: PromoteEnv = {}): RevertResult {
  const home = env.home ?? getGearHome();
  const now = env.now ?? new Date();
  const entries = readLedger(home);
  const active = activePromotions(entries); // newest first
  if (active.length === 0) {
    return {
      ok: false,
      reverted: [],
      refusals: ["nothing to revert: no promotion is standing."],
      halted: haltState(entries).halted,
    };
  }
  const target = active.slice(0, Math.max(1, n));
  for (const p of target) {
    appendLedger(
      {
        v: 1,
        at: now.toISOString(),
        kind: "revert",
        subject: p.subject,
        treatmentConfigHash: p.treatmentConfigHash,
        configLines: p.configLines,
        note: `reverted the promotion of ${p.at.slice(0, 10)}`,
      },
      home,
    );
  }
  const after = readLedger(home);
  const path = writeConfig(home, activePromotions(after));
  const halt = haltState(after);
  if (halt.halted) {
    // Recorded so `status` and the next `promote` both read it from the file
    // rather than recomputing a policy decision in two places.
    appendLedger(
      { v: 1, at: now.toISOString(), kind: "halt", subject: "loop", note: halt.reason },
      home,
    );
  }
  return {
    ok: true,
    reverted: target.map((p) => p.subject),
    refusals: [],
    configPath: path,
    halted: halt.halted,
    haltReason: halt.reason,
  };
}

/** Clear a halt. A human act, recorded like every other. */
export function resume(env: PromoteEnv = {}): boolean {
  const home = env.home ?? getGearHome();
  const now = env.now ?? new Date();
  if (!haltState(readLedger(home)).halted) return false;
  appendLedger(
    { v: 1, at: now.toISOString(), kind: "halt", subject: "loop", note: "resumed" },
    home,
  );
  return true;
}
