import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { LlmGateway, ProviderName } from "@gear/llm-gateway";
import type { ToolCallInput, ToolCallOutput, ToolHandler, ToolSchema } from "@gear/tool-registry";
import type { ToolResultProcessor } from "./agent-loop";
import { planResearch, runResearch } from "./research";
import type { PlanResearchOpts, ResearchDeps } from "./research";
import { isClarification } from "./research-types";
import type { ResearchDepth, ResearchOptions, ResearchReport } from "./research-types";
import { workspaceConfigPath } from "@gear/shared";

/**
 * `research` — the /research | /deepresearch pipeline as a model-invocable
 * tool, so "do deep research on X" asked in plain chat runs the REAL
 * multi-source engine (plan → parallel web investigators → cited long-form
 * synthesis) instead of degrading to an ordinary single-model answer.
 *
 * Differences from the slash-command flow, by design:
 * - No interactive plan-approval gate — the model initiated the run, so the
 *   plan auto-approves (the permission prompt on this tool is the human gate).
 * - No clarifying-questions round (allowClarification: false): an ambiguous
 *   query still yields a usable plan; the model refines by re-calling.
 * The finished report is saved to the same place /research saves
 * (`<workspace>/.gear/research/`), and the same session audit events are
 * recorded, so follow-ups like /interactive work identically.
 */

export interface ResearchToolDeps {
  /** Path to the compiled gear-tools binary (read tools for local scopes). */
  binaryPath: string;
  workspaceRoot: string;
  /**
   * Live resolver called at EXECUTE time: hands over the CURRENT gateway (the
   * engine rebuilds it on key edits) and the active model/provider.
   */
  resolve: () => { gateway: LlmGateway; model: string; provider: ProviderName };
  /** The engine's `[research]` config defaults (depth, save, outputDir). */
  defaults?: () => ResearchOptions;
  /** Prompt-injection screening for investigator web/file results. */
  toolResultProcessor?: ToolResultProcessor;
  /** Persist a session audit event (research_plan / research_report). */
  record?: (
    sessionId: string,
    type: "research_plan" | "research_report",
    payload: Record<string, unknown>,
  ) => void;
}

export const RESEARCH_TOOL_SCHEMA: ToolSchema = {
  name: "research",
  version: "0.1.0",
  description:
    "Run a full deep-research investigation — the same engine behind /research and " +
    "/deepresearch: plans sub-questions, fans out parallel web investigators, and " +
    "synthesizes a long-form cited markdown report (auto-saved under .gear/research/). " +
    "Use when the user asks for research, a deep dive, a survey/comparison of external " +
    "options, or a cited report — NOT for questions answerable from this codebase or " +
    "one quick web_search. depth: 'quick' fast lookup, 'standard' sectioned report " +
    "(default), 'deep' the heavy multi-round investigation (use when the user says " +
    "deep research). This runs for minutes: tell the user you are starting it BEFORE " +
    "the call, and afterwards present the key findings plus the saved report path.",
  inputSchema: {
    type: "object",
    properties: {
      query: {
        type: "string",
        description: "The research question — self-contained, specific, in the user's terms.",
      },
      depth: {
        type: "string",
        enum: ["quick", "standard", "deep"],
        description: "Investigation depth. Omit to use the configured default (standard).",
      },
    },
    required: ["query"],
  },
  permissionLevel: "confirm",
  category: "network",
};

/** Save the report like the /research flow does; returns the path or null. */
function saveReport(
  workspaceRoot: string,
  cfg: ResearchOptions,
  report: ResearchReport,
): string | null {
  if (cfg.save === false) return null;
  try {
    const dir = cfg.outputDir || workspaceConfigPath(workspaceRoot, "research");
    mkdirSync(dir, { recursive: true });
    const slug =
      report.question
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-+|-+$/g, "")
        .slice(0, 50) || "research";
    const file = join(dir, `${new Date().toISOString().slice(0, 10)}-${slug}.md`);
    const body = `# Research: ${report.question}\n\n_Generated by Gear · ${new Date().toISOString()}_\n\n${report.markdown}\n`;
    writeFileSync(file, body);
    return file;
  } catch {
    return null; // saving is best-effort; the report still returns inline
  }
}

export function createResearchTool(deps: ResearchToolDeps): ToolHandler {
  return {
    schema: RESEARCH_TOOL_SCHEMA,

    validate: (args) => {
      if (typeof args.query !== "string" || args.query.trim().length === 0) {
        return { valid: false, error: "query is required and must be a non-empty string" };
      }
      if (
        args.depth !== undefined &&
        !["quick", "standard", "deep"].includes(args.depth as string)
      ) {
        return { valid: false, error: "depth must be one of: quick, standard, deep" };
      }
      return { valid: true };
    },

    execute: async (input: ToolCallInput): Promise<ToolCallOutput> => {
      const start = performance.now();
      const fail = (error: string): ToolCallOutput => ({
        callId: input.callId,
        toolName: input.toolName,
        success: false,
        result: "",
        error,
        durationMs: Math.round(performance.now() - start),
      });

      try {
        const { query, depth } = input.args as { query: string; depth?: ResearchDepth };
        const live = deps.resolve();
        const cfg = deps.defaults?.() ?? {};
        const opts: PlanResearchOpts = {
          ...cfg,
          ...(depth ? { depth } : {}),
          allowClarification: false,
        };
        const rdeps: ResearchDeps = {
          gateway: live.gateway,
          binaryPath: deps.binaryPath,
          model: live.model,
          provider: live.provider,
          workspaceRoot: deps.workspaceRoot,
          sessionId: input.sessionId,
          toolResultProcessor: deps.toolResultProcessor,
        };

        const plan = await planResearch(rdeps, query.trim(), opts, input.signal);
        if (isClarification(plan)) {
          // allowClarification:false makes this unreachable in practice, but a
          // defensive path beats a crash if the planner contract ever drifts.
          return fail(
            `The research planner needs a more specific query. It asked: ${plan.questions.join(" | ")} — re-call with those answered in the query.`,
          );
        }
        deps.record?.(input.sessionId, "research_plan", { plan });

        let report: ResearchReport | null = null;
        let lastError: string | null = null;
        for await (const ev of runResearch(rdeps, plan, opts, input.signal)) {
          if (ev.type === "research_complete") report = ev.report;
          else if (ev.type === "error") lastError = ev.error;
        }

        if (!report) {
          return fail(
            input.signal?.aborted
              ? "Research aborted."
              : (lastError ?? "Research produced no report."),
          );
        }

        const file = saveReport(deps.workspaceRoot, cfg, report);
        deps.record?.(input.sessionId, "research_report", {
          question: report.question,
          sources: report.sources.map((s) => ({ index: s.index, title: s.title, url: s.url })),
          completed: report.completed,
          failed: report.failed,
          warnings: report.warnings,
        });

        const header = [
          `Research complete — "${report.question}"`,
          `${report.sources.length} sources · ${report.completed} sub-question(s) completed` +
            (report.failed > 0 ? `, ${report.failed} failed` : ""),
          ...(file ? [`Full report saved to: ${file}`] : []),
          ...(report.warnings.length > 0 ? [`Warnings: ${report.warnings.join("; ")}`] : []),
        ].join("\n");

        return {
          callId: input.callId,
          toolName: input.toolName,
          success: true,
          result: `${header}\n\n${report.markdown}`,
          durationMs: Math.round(performance.now() - start),
        };
      } catch (err) {
        return fail(err instanceof Error ? err.message : String(err));
      }
    },
  };
}
