// ─── The contract of the GENERATED web-bundle manifest ───
//
// `scripts/gen-web-embed.ts` writes the sibling `generated.js` from a built
// `apps/web/dist`: one `import … with { type: "file" }` per asset, so that
// `bun build --compile` copies the bytes into the executable, plus the path
// map below. That file is a build artifact — gitignored, prettier-ignored,
// regenerated by every build path. This declaration is the committed half.
//
// Why a `.js` next to a `.d.ts` rather than one `.ts`: tsc resolves
// `./generated` to THIS file (it never considers `.js` with `allowJs` off) and
// so never has to understand Bun's `type: "file"` import attribute, which it
// would reject. Bun's resolver ignores `.d.ts` and takes `generated.js`. Both
// toolchains get the file they can read, and `bun run typecheck` stays green
// on a checkout that has never built the client.

/**
 * Every file of the built client, keyed by its path relative to `dist/`
 * (`index.html`, `assets/index-Di0j9cAO.css`, …).
 *
 * The values are paths a `Bun.file()` can open: inside the compiled binary
 * they are `/$bunfs/root/…`, from a source run they are the real files.
 */
export declare const WEB_EMBED: Record<string, string>;

/** ISO timestamp of the generation, for `gear serve --check` and banners. */
export declare const WEB_EMBED_BUILT_AT: string;
