import { describe, expect, test } from "bun:test";
import { isVerificationCommand } from "../../../packages/orchestrator/src/brief";

describe("verification commands name a check that actually executes", () => {
  test.each([
    "node browser-test.mjs",
    "node scripts/verify-ui.js",
    "node --test tests/parser.test.mjs",
    "bun tests/parser.test.ts",
    "bun run scripts/validate.ts",
    "python3 scripts/check_output.py",
    "python -m pytest tests",
    "bash scripts/smoke-test.sh",
    "./scripts/verify.sh",
    "node 'scripts with spaces/browser-test.mjs'",
    "FIELDNOTES_SCREENSHOTS=0 node browser-test.mjs",
    "env CI=1 node browser-test.mjs",
    "cd app && node browser-test.mjs && git diff --check",
    "node browser-test.mjs && printf 'complete\\n'",
    "node browser-test.mjs >check.log 2>&1",
    "bun test </dev/null",
    "node browser-test.mjs # record the exit",
    "cd app; node browser-test.mjs",
    "npm run test:e2e -- --project=chromium",
    "pnpm --filter app run typecheck",
    "yarn lint",
    "bunx tsc --noEmit",
    "npx playwright test",
    "cargo test --workspace",
    "cargo +stable clippy --all-targets",
    "go test ./...",
    "swift test",
    "./gradlew test",
    "mvn verify",
    "make check",
    "turbo typecheck",
    "turbo run test --filter=@rune/orchestrator",
    "nx test app",
    "git diff --check",
    `git diff --check && test "$(git status --short | wc -l | tr -d ' ')" = 2 && git status --short`,
    `git diff --check && test "$(git status --short | awk '{print $2}' | sort | tr '\\n' ' ')" = "csv.test.ts csv.ts " && bun -e 'import { parseCsv } from "./csv.ts"; if (typeof parseCsv !== "function") process.exit(1)'`,
    `test "$(printf '%s' "$(cat output.txt)")" = ready`,
    `test "$(printf '%s' 'a)b')" = 'a)b'`,
    'test "`cat output.txt`" = ready',
    "EXPECTED=$(cat expected.txt) node browser-test.mjs",
    'test "$((1 + (2)))" = 3',
  ])("records %s", (command) => {
    expect(isVerificationCommand(command)).toBe(true);
  });

  test.each([
    "echo test",
    "printf 'node browser-test.mjs'",
    "echo 'one; node browser-test.mjs'",
    "cat browser-test.mjs",
    "rg test package.json",
    "node app.mjs browser-test.mjs",
    "node -e 'console.log(\"test\")'",
    "node --help browser-test.mjs",
    "node --require browser-test.mjs app.mjs",
    "node --test --list-tests",
    "npm install test",
    "npm exec echo test",
    "git show HEAD:browser-test.mjs",
    "node scripts/contest.mjs",
    "node scripts/latest.mjs",
    "node browser-test.mjs || true",
    "node browser-test.mjs; echo done",
    "node browser-test.mjs | tee result.log",
    "node browser-test.mjs &",
    "node browser-test.mjs &&",
    "make -f build",
    "turbo dev",
    "nx serve app",
    "xcodebuild -list",
    "echo $(node browser-test.mjs)",
    'echo "$(node browser-test.mjs)"',
    'echo "`node browser-test.mjs`"',
    'echo $(printf "%s" "$(node browser-test.mjs)")',
    "$(echo node) browser-test.mjs",
    'node "$(echo browser)-test.mjs"',
    'bun run "test:$(echo unit)"',
    'test "$(cat output.txt)" = ready || true',
    'test "$(cat output.txt)" = ready | tee check.log',
    'test "$(cat output.txt)" = ready; echo done',
    'test "$(cat output.txt)" = ready &',
    'test "$(cat output.txt" = ready',
    'test "`cat output.txt" = ready',
    'echo "$(case x in x) echo test;; esac)"',
    "# node browser-test.mjs",
    "node 'browser-test.mjs",
  ])("does not turn output, inspection or a masked exit into a check: %s", (command) => {
    expect(isVerificationCommand(command)).toBe(false);
  });
});
