// (protocol.ts — a JSON-RPC wire spec nothing ever imported — was removed in
// the phase-0 stabilization; the real host wire format lives in host-client.ts.)
export {
  parseToolArguments,
  tryParseJson,
  setToolArgsSalvageListener,
  type ToolArgsSalvageInfo,
} from "./json.js";
export {
  INCIDENT_CLASSES,
  SEVERITY_RANK,
  incidentFamily,
  normalizeForFingerprint,
  fingerprintIncident,
  type IncidentClass,
  type IncidentSeverity,
  type IncidentOutcome,
  type IncidentContext,
  type IncidentInput,
  type IncidentRecord,
  type IncidentReporter,
  type TrailEntry,
} from "./incident.js";
export {
  type RuneConfig,
  type PermissionRule,
  type ConfigScope,
  type SetConfigResult,
  loadConfig,
  getConfigFilePath,
  setConfigValue,
} from "./config.js";
export {
  type ProviderKind,
  type ProviderPreset,
  type AuthMethod,
  type ProviderCapabilities,
  type ProviderDescriptor,
  type ProviderCapacity,
  PROVIDER_PRESETS,
  AUTO_PROVIDER_PRIORITY,
  PROVIDER_CAPACITY,
  FALLBACK_CAPACITY_ORDER,
  providerFallbackRank,
  normalizeFallbackOrder,
  type QuotaPolicy,
  normalizeModelIntegrity,
  normalizeQuotaPolicy,
  CUSTOM_PROVIDER_ID,
  getPreset,
  getProviderDescriptor,
  effectiveAuthMethods,
  authMethodLabel,
  accountLoginLabel,
} from "./providers.js";
export {
  type CredentialBackend,
  type CredentialStore,
  type CredentialCommandRunner,
  type CredentialCommandResult,
  type OpenCredentialStoreOpts,
  type MigrationResult,
  CREDENTIAL_SERVICE,
  FileCredentialStore,
  openCredentialStore,
  describeCredentialBackend,
  apiKeyAccount,
  oauthAccount,
  hasStoredCredential,
  migrateLegacySecrets,
} from "./credential-store.js";
export {
  type CustomEndpoint,
  type SecretsFile,
  type StoredKey,
  getSecretsPath,
  loadSecrets,
  saveSecrets,
  setProviderKey,
  addProviderKey,
  removeProviderKey,
  setActiveProviderKey,
  clearProviderKey,
  providerKeyEntries,
  genKeyId,
  setCustomEndpoint,
  clearCustomEndpoint,
  setProviderDisabled,
  setLocalEndpoint,
  maskKey,
  secretsArePrivate,
  type SearchKeyPreset,
  type SearchKeyStatusRow,
  SEARCH_KEY_PRESETS,
  searchKeyStatus,
  applySearchKeysToEnv,
} from "./secrets.js";
export { type LastModel, getModelStatePath, loadLastModel, saveLastModel } from "./model-store.js";
export {
  type CachedModel,
  MODEL_CACHE_TTL_MS,
  getModelCachePath,
  loadCachedModels,
  saveCachedModels,
  clearCachedModels,
  cachedModelsAge,
  describeAge,
} from "./model-catalog.js";
export {
  type SessionPrefs,
  getPrefsPath,
  loadPrefs,
  savePrefs,
  mayPersistGear,
  shouldAskAboutFourthGear,
} from "./prefs-store.js";
export { loadSavedSandboxState, resolveInitialSandbox, saveSandboxState } from "./sandbox-store.js";
export { loadSavedBrowserState, resolveInitialBrowser, saveBrowserState } from "./browser-store.js";
export {
  type ModelTier,
  type SubagentMode,
  type TierRef,
  type TiersConfig,
  PROVIDER_TIER_DEFAULTS,
  normalizeSubagentEffort,
  normalizeSubagentMode,
  parseTierRef,
  resolveTier,
} from "./tiers.js";
export { type LogLevel, type Logger, createLogger, nullLogger } from "./logger.js";
export {
  type MemoryScheduleKind,
  type ParsedSchedule,
  type SystemMemoryMeta,
  type SystemMemory,
  getSystemMemoryPath,
  getSystemMemoryMetaPath,
  loadSystemMemory,
  loadSystemMemoryMeta,
  saveSystemMemory,
  saveSystemMemoryMeta,
  clearSystemMemory,
  parseSchedule,
  describeSchedule,
  isReflectionDue,
  effectiveSchedule,
  estimateMemoryTokens,
  clampToBudget,
} from "./system-memory.js";
export * from "./session.js";
export {
  type RunState,
  type CheckpointVersion,
  type CheckpointPolicy,
  type CheckpointStore,
  DEFAULT_CHECKPOINT_POLICY,
  SqliteCheckpointStore,
} from "./state.js";
export { CHECKPOINT_INDEXES, AUDIT_INDEXES, SESSION_INDEXES, applyIndexes } from "./schema.js";
export {
  type RuneAccentName,
  type RuneBaseName,
  type RuneBaseCss,
  type RuneTerminalPalette,
  type Rgb,
  RUNE_PALETTE,
  RUNE_STATUS_COLORS,
  STATUS_CONTRAST_FLOOR,
  ACCENT_CONTRAST_FLOOR,
  accentFor,
  contrastRatio,
  relativeLuminance,
  readableOn,
  RUNE_ACCENT_NAMES,
  RUNE_ACCENT_LABELS,
  RUNE_BASE_CSS,
  RUNE_ACCENT_CSS,
  runeTerminalPalette,
  runeAccentHex,
  runeTerminalRoles,
  solidOver,
  mixToward,
  hexToRgbTuple,
  rgbTupleToHex,
} from "./design-tokens.js";
export {
  adoptLegacyEnv,
  ensureRuneHome,
  runeHomePath,
  getRuneHome,
  isPathInside,
  migrateLegacyHome,
  resetRuneHomeCache,
  takeHomeMigrationNote,
  usesLegacyWorkspaceDir,
  workspaceConfigDir,
  workspaceConfigPath,
  RUNE_HOME_DIRNAME,
  RUNE_WS_DIRNAME,
  RUNE_DB_FILENAME,
  RUNE_MEMORY_FILENAME,
  LEGACY_HOME_DIRNAMES,
  LEGACY_WS_DIRNAMES,
  LEGACY_DB_FILENAMES,
  LEGACY_MEMORY_FILENAMES,
  LEGACY_ENV_PREFIX,
} from "./paths.js";
