// ─── Generate the manifest that carries the web client into the binary ───
//
// Reads a built `apps/web/dist` and writes
// `packages/orchestrator/src/web-embed/generated.js`: one
// `import … with { type: "file" }` per asset — the syntax `bun build
// --compile` looks for when deciding what to copy into the executable — plus
// the map from `dist`-relative path to whatever the import evaluated to
// (`/$bunfs/root/…` in a compiled binary, the real file in a source run).
//
// It is a build artifact: gitignored, prettier-ignored, and rewritten by every
// path that compiles a binary (`scripts/install.sh`, `scripts/build-release.sh`,
// release.yml's CLI job, ci.yml's `packaged-e2e`). What is committed is this
// generator and the `.d.ts` that gives tsc the module's shape.
//
// It FAILS if there is no bundle. Shipping a binary that cannot serve the
// product is the defect this exists to close, and a generator that quietly
// wrote an empty map would reintroduce it one CI edit later.
//
//   bun scripts/gen-web-embed.ts            # from the repo root
//   bun scripts/gen-web-embed.ts --check    # report only, write nothing

import { existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";

const ROOT = resolve(dirname(new URL(import.meta.url).pathname), "..");
const DIST = join(ROOT, "apps", "web", "dist");
const OUT = join(ROOT, "packages", "orchestrator", "src", "web-embed", "generated.js");
const checkOnly = process.argv.includes("--check");

/** Every file under `dir`, as paths relative to it, with `/` separators. */
function walk(dir: string, base = dir): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...walk(full, base));
    else out.push(relative(base, full).split(sep).join("/"));
  }
  return out;
}

if (!existsSync(join(DIST, "index.html"))) {
  console.error(`✗ no web client at ${DIST}`);
  console.error(`  build it first:  bun run --filter @gear/web build`);
  console.error(`  a binary compiled without it cannot serve the product.`);
  process.exit(1);
}

const files = walk(DIST).sort();
if (checkOnly) {
  console.log(`✓ ${files.length} file(s) in ${DIST}`);
  process.exit(0);
}

/**
 * The import specifier for one asset, relative to the generated file.
 *
 * Always explicitly relative: `dist/` sits four directories up from
 * `web-embed/`, so every path already begins `../`, but a specifier that did
 * not start with `.` or `/` would be read as a package name.
 */
const specifier = (f: string): string => {
  const path = relative(dirname(OUT), join(DIST, f)).split(sep).join("/");
  return path.startsWith(".") ? path : `./${path}`;
};

const imports: string[] = [];
const entries: string[] = [];
files.forEach((file, i) => {
  imports.push(`import f${i} from ${JSON.stringify(specifier(file))} with { type: "file" };`);
  entries.push(`  ${JSON.stringify(file)}: f${i},`);
});

const source = `// GENERATED by scripts/gen-web-embed.ts — do not edit, do not commit.
// ${files.length} file(s) from apps/web/dist. See packages/orchestrator/src/web-embed/generated.d.ts.
${imports.join("\n")}

export const WEB_EMBED = {
${entries.join("\n")}
};

export const WEB_EMBED_BUILT_AT = ${JSON.stringify(new Date().toISOString())};
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, source);
console.log(`✓ web embed manifest: ${files.length} file(s) → ${relative(ROOT, OUT)}`);
