// ─── Desktop/web token emitter ───
//
// Emits `apps/desktop/src/styles/tokens.css` from the ONE pigment source,
// `packages/shared/src/design-tokens.ts`, which is the machine-readable form of
// the Savoir brand DNA.
//
// The attribute API is unchanged, because the stylesheet and the components
// already speak it and renaming a vocabulary is not a rebrand:
//
//   [data-theme-base="light"|"dark"]   → the ground
//   [data-accent="datum"]              → the accent (one, now)
//
// `[data-accent]` survives with a single value on purpose. It is the hidden
// `[ui] accent` override the customizer still wants, and a seam that says "this
// was a choice, and the choice is one" is more honest than deleting it.
//
// Usage:  bun run scripts/generate-tokens-css.ts [outfile]

import { writeFileSync } from "fs";
import {
  GEAR_ACCENT_NAMES,
  GEAR_ACCENT_CSS,
  GEAR_BASE_CSS,
  GEAR_SCALE,
  SAVOIR,
  type GearBaseName,
} from "../packages/shared/src/design-tokens";

const CSS_NAME: Record<keyof (typeof GEAR_BASE_CSS)["light"], string> = {
  canvasBg: "--canvas-bg",
  cardBg: "--card-bg",
  textMain: "--text-main",
  textSub: "--text-sub",
  textMuted: "--text-muted",
  textFaint: "--text-faint",
  ochre: "--ochre",
  green: "--green",
  red: "--red",
  barBg: "--bar-bg",
  barHover: "--bar-hover",
  barActive: "--bar-active",
  hairline: "--hairline",
  codeBg: "--code-bg",
  codeTag: "--code-tag",
  diffBg: "--diff-bg",
  diffHdr: "--diff-hdr",
  popoverBg: "--popover-bg",
  kbdBg: "--kbd-bg",
};

/** The brand's own names, alongside the surface vocabulary above. */
const SAVOIR_NAME: Array<[string, string]> = [
  ["--paper", SAVOIR.paper],
  ["--paper-2", SAVOIR.paper2],
  ["--paper-muted", SAVOIR.paperMuted],
  ["--ink", SAVOIR.ink],
  ["--ink-2", SAVOIR.ink2],
  ["--surface-dark", SAVOIR.surfaceDark],
  ["--graphite", SAVOIR.graphite],
  ["--graphite-2", SAVOIR.graphite2],
  ["--line", SAVOIR.line],
  ["--line-dark", SAVOIR.lineDark],
  ["--datum", SAVOIR.datum],
  ["--datum-deep", SAVOIR.datumDeep],
  ["--signal", SAVOIR.signal],
  ["--on-datum", SAVOIR.onDatum],
  ["--caution", SAVOIR.caution],
  ["--negative", SAVOIR.negative],
];

function baseBlock(base: GearBaseName): string {
  const css = GEAR_BASE_CSS[base];
  const rows = (Object.keys(CSS_NAME) as Array<keyof typeof CSS_NAME>)
    .map((key) => `  ${CSS_NAME[key]}: ${css[key]};`)
    .join("\n");
  // The graticule is drawn from the ground's own ink, so it reads as texture in
  // the paper rather than as a grey overlay bolted on top.
  const grid = base === "light" ? "rgba(20, 22, 26, 0.035)" : "rgba(231, 232, 227, 0.035)";
  return `[data-theme-base="${base}"] {\n  color-scheme: ${base};\n${rows}\n  --graticule-ink: ${grid};\n}`;
}

function accentBlocks(): string {
  const blocks: string[] = [];
  for (const accent of GEAR_ACCENT_NAMES) {
    const light = GEAR_ACCENT_CSS.light[accent];
    const dark = GEAR_ACCENT_CSS.dark[accent];
    // The derived tints are alpha of the accent itself — never a second hue.
    blocks.push(
      `[data-accent="${accent}"] {\n` +
        `  --accent: ${light};\n` +
        `  --accent-bg: color-mix(in srgb, ${light} 8%, transparent);\n` +
        `  --accent-bd: color-mix(in srgb, ${light} 30%, transparent);\n` +
        `}`,
    );
    blocks.push(
      `[data-theme-base="dark"][data-accent="${accent}"] {\n` +
        `  --accent: ${dark};\n` +
        `  --accent-bg: color-mix(in srgb, ${dark} 12%, transparent);\n` +
        `  --accent-bd: color-mix(in srgb, ${dark} 34%, transparent);\n` +
        `}`,
    );
  }
  return blocks.join("\n\n");
}

export function renderTokensCss(): string {
  return [
    "/* Generated by scripts/generate-tokens-css.ts — DO NOT EDIT.",
    " * Source of truth: packages/shared/src/design-tokens.ts (the Savoir brand DNA).",
    " * Two grounds, one accent, no shadows, 3px radii. */",
    "",
    ":root {",
    `  --sans: ${GEAR_SCALE.sans};`,
    `  --mono: ${GEAR_SCALE.mono};`,
    `  --ease: ${GEAR_SCALE.ease};`,
    "",
    "  /* One radius. A pill is round; the icon tile is the single 6px corner. */",
    `  --r: ${GEAR_SCALE.radius};`,
    `  --r-pill: ${GEAR_SCALE.radiusPill};`,
    `  --r-tile: ${GEAR_SCALE.radiusTile};`,
    "  /* The old scale names, all resolved to the one radius, so a rule that",
    "     still asks for --r-card gets 3px instead of a 20px throwback. */",
    `  --r-card: ${GEAR_SCALE.radius};`,
    `  --r-panel: ${GEAR_SCALE.radius};`,
    `  --r-item: ${GEAR_SCALE.radius};`,
    `  --r-chip: ${GEAR_SCALE.radius};`,
    "",
    `  --graticule: ${GEAR_SCALE.graticule};`,
    `  --label-tracking: ${GEAR_SCALE.labelTracking};`,
    `  --display-tracking: ${GEAR_SCALE.displayTracking};`,
    "",
    "  /* The brand's own names, for anything written against the DNA directly. */",
    ...SAVOIR_NAME.map(([name, value]) => `  ${name}: ${value};`),
    "}",
    "",
    baseBlock("light"),
    "",
    baseBlock("dark"),
    "",
    accentBlocks(),
    "",
  ].join("\n");
}

if (import.meta.main) {
  const out = process.argv[2];
  const css = renderTokensCss();
  if (out) {
    writeFileSync(out, css);
    console.log(`wrote ${out} (${css.length} bytes)`);
  } else {
    console.log(css);
  }
}
