// ─── The primitive catalogue, as documentation ───
//
// Emits `docs/primitives.md` from the catalogue itself: the same
// `PRIMITIVES` map the composer validates against and the gallery renders, and
// the same zod introspection the gallery uses to show a schema beside a
// primitive.
//
// Generated rather than written for the reason §0.3 gives — a stale doc is a
// defect — and this is the doc most likely to go stale, because it has thirty
// entries and every one of them changes whenever a prop is added. A table
// somebody maintains by hand is a second source of truth; this one cannot
// disagree with the code because it IS the code, printed.
//
// `tests/unit/web/primitives-schema.test.ts` fails if the committed file is not
// what this script produces.
//
// Usage:  bun run scripts/generate-primitives-doc.ts [outfile]

import { writeFileSync } from "fs";

import { BLOCK_TYPES, PRIMITIVES } from "../apps/web/src/primitives/index";
import { describeSchema } from "../apps/web/src/primitives/describe";

const HEADER = `<!-- Generated by scripts/generate-primitives-doc.ts — DO NOT EDIT.
     Source of truth: apps/web/src/primitives/index.ts and each primitive's zod schema.
     Regenerate with: bun run scripts/generate-primitives-doc.ts docs/primitives.md -->

# The primitive catalogue

Thirty React components with strict prop schemas — the closed vocabulary the agent
composes a task surface from. A projection block names a \`type\`; if the name is not
in this table the block does not exist, and there is no path from model output to the
DOM that avoids that check.

Every primitive has **four states**: \`ready\`, \`empty\` (its data is present and has
nothing in it), \`loading\` (\`state: "loading"\`) and \`error\` (\`state: "error"\` plus
\`error\`). Every one renders on both grounds from \`tokens.css\`, is reachable by
keyboard through real \`<button>\` and \`<a>\` elements, carries no \`box-shadow\` on
content, and takes its radii from {6, 8, 10}. **No primitive accepts raw HTML except
Preview**, which renders in a sandboxed iframe.

See [composition.md](composition.md) for the projection schema and the six personas,
and \`/gallery\` (served by \`gear serve --web\`, linked from nowhere in the product) for
all thirty in every state on both grounds.

## The base props

Spread into every primitive's schema, flat rather than nested, because a projection
block's props are flat on the wire:

| prop | type | meaning |
| --- | --- | --- |
| \`label\` | \`string?\` | the accessible name and the visible eyebrow |
| \`state\` | \`"ready" \\| "loading" \\| "error"\` (optional) | the block's LOAD state |
| \`error\` | \`string?\` | what failed, shown in the error state |

It is \`state\` and not \`status\` deliberately: four primitives have a domain status of
their own — a hypothesis is \`refuted\`, an agent is \`working\` — and P11.1 names that
field \`status\` on the task state, so a base key called \`status\` would overwrite a
verdict with a load state on every one of them.

## Binding

\`bind\` on a block resolves a dotted state path; how the value becomes props is the
primitive's own \`bind.mode\`:

| mode | what happens |
| --- | --- |
| \`assign\` | \`props[key] = value\` — a list into \`rows\`, \`items\`, \`points\` |
| \`merge\` | \`props = { …props, …value }\` — an object of fields |
| \`repeat\` | one component per array element, the element spread over the block's props |
| \`none\` | the primitive takes no live data |

\`foldable\` marks the primitives that honour a \`folded\` prop, which is what lets
\`foldWhen\` be a closed predicate rather than a callback. \`interactive\` marks the ones
that take callbacks the projection cannot supply; the shell wires those.

## The thirty
`;

function table(): string {
  const rows = BLOCK_TYPES.map((type, i) => {
    const e = PRIMITIVES[type];
    const flags = [e.foldable ? "foldable" : null, e.interactive ? "interactive" : null]
      .filter(Boolean)
      .join(", ");
    const bind = e.bind.key ? `${e.bind.mode} → \`${e.bind.key}\`` : e.bind.mode;
    return `| ${String(i + 1).padStart(2, "0")} | \`${type}\` | ${e.summary} | ${bind} | ${flags || "—"} |`;
  });
  return [
    "",
    "| # | type | what it is for | bind | |",
    "| --- | --- | --- | --- | --- |",
    ...rows,
    "",
  ].join("\n");
}

function schemas(): string {
  const out: string[] = ["## The schemas", ""];
  for (const type of BLOCK_TYPES) {
    const e = PRIMITIVES[type];
    const fields = describeSchema(e.schema);
    out.push(`### \`${type}\` — ${e.title}`, "", e.summary, "");
    out.push("| prop | type | |", "| --- | --- | --- |");
    for (const f of fields) {
      const t = f.type.replace(/\|/g, "\\|");
      out.push(`| \`${f.name}\` | \`${t}\` | ${f.optional ? "optional" : "required"} |`);
    }
    out.push("");
  }
  return out.join("\n");
}

function raw(): string {
  return [HEADER, table(), schemas()].join("\n").replace(/\n{3,}/g, "\n\n");
}

/**
 * The doc, formatted the way the repository formats everything else.
 *
 * Not cosmetic, and the same reasoning as `generate-tokens-css.ts`: `format:check`
 * runs over the whole tree, so a generated file prettier disagrees with turns
 * "regenerate the doc" into "regenerate the doc and then remember to format it",
 * which is the step somebody forgets on the one commit where it matters. The
 * unit test compares the committed file against THIS, so the formatter is part
 * of the contract rather than a thing applied afterwards.
 */
export async function renderPrimitivesDoc(): Promise<string> {
  const md = raw();
  try {
    const prettier = (await import("prettier")) as {
      format: (source: string, opts: Record<string, unknown>) => Promise<string>;
      resolveConfig: (p: string) => Promise<Record<string, unknown> | null>;
    };
    const config = (await prettier.resolveConfig("docs/primitives.md")) ?? {};
    return await prettier.format(md, { ...config, parser: "markdown" });
  } catch {
    return md; // no prettier: the doc is still correct, just unformatted
  }
}

if (import.meta.main) {
  const out = process.argv[2];
  const md = await renderPrimitivesDoc();
  if (out) {
    writeFileSync(out, md);
    console.log(`wrote ${out} (${md.length} bytes)`);
  } else {
    console.log(md);
  }
}
