// ─── Desktop token emitter (Phase 0 tooling — not yet wired into the app) ───
//
// Emits CSS custom properties from packages/shared/src/design-tokens.ts using
// the SAME attribute API as gear-customizer-v2.html:
//
//   [data-theme-base="light"|"dark"]              → base surface variables
//   [data-accent="<name>"]                        → light accent
//   [data-theme-base="dark"][data-accent="<name>"] → dark accent override
//
// Usage:  bun run scripts/generate-tokens-css.ts [outfile]
// Prints to stdout when no outfile is given. The desktop re-skin (Phase 2)
// consumes this as apps/desktop/src/styles/tokens.css; until then the script
// exists so the token pipeline is complete and testable end to end.

import { writeFileSync } from "fs";
import {
  GEAR_ACCENT_NAMES,
  GEAR_ACCENT_CSS,
  GEAR_BASE_CSS,
  GEAR_SCALE,
  type GearBaseName,
} from "../packages/shared/src/design-tokens";

const CSS_NAME: Record<keyof (typeof GEAR_BASE_CSS)["light"], string> = {
  canvasBg: "--canvas-bg",
  cardBg: "--card-bg",
  textMain: "--text-main",
  textSub: "--text-sub",
  textMuted: "--text-muted",
  textFaint: "--text-faint",
  ochre: "--ochre",
  green: "--green",
  red: "--red",
  barBg: "--bar-bg",
  barHover: "--bar-hover",
  barActive: "--bar-active",
  hairline: "--hairline",
  codeBg: "--code-bg",
  codeTag: "--code-tag",
  diffBg: "--diff-bg",
  diffHdr: "--diff-hdr",
  popoverBg: "--popover-bg",
  kbdBg: "--kbd-bg",
};

function baseBlock(base: GearBaseName): string {
  const css = GEAR_BASE_CSS[base];
  const rows = (Object.keys(CSS_NAME) as Array<keyof typeof CSS_NAME>)
    .map((key) => `  ${CSS_NAME[key]}: ${css[key]};`)
    .join("\n");
  return `[data-theme-base="${base}"] {\n  color-scheme: ${base};\n${rows}\n}`;
}

function accentBlocks(): string {
  const blocks: string[] = [];
  for (const accent of GEAR_ACCENT_NAMES) {
    blocks.push(`[data-accent="${accent}"] {\n  --accent: ${GEAR_ACCENT_CSS.light[accent]};\n}`);
    blocks.push(
      `[data-theme-base="dark"][data-accent="${accent}"] {\n  --accent: ${GEAR_ACCENT_CSS.dark[accent]};\n}`,
    );
  }
  return blocks.join("\n\n");
}

export function renderTokensCss(): string {
  return [
    "/* Generated by scripts/generate-tokens-css.ts — DO NOT EDIT.",
    " * Source of truth: packages/shared/src/design-tokens.ts",
    " * Contract: gear-customizer-v2.html (parity-tested). */",
    "",
    ":root {",
    `  --mono: ${GEAR_SCALE.fontMono};`,
    `  --ease: ${GEAR_SCALE.ease};`,
    `  --r-card: ${GEAR_SCALE.radiusCard};`,
    `  --r-panel: ${GEAR_SCALE.radiusPanel};`,
    `  --r-item: ${GEAR_SCALE.radiusItem};`,
    `  --r-chip: ${GEAR_SCALE.radiusChip};`,
    "}",
    "",
    baseBlock("light"),
    "",
    baseBlock("dark"),
    "",
    accentBlocks(),
    "",
  ].join("\n");
}

if (import.meta.main) {
  const out = process.argv[2];
  const css = renderTokensCss();
  if (out) {
    writeFileSync(out, css);
    console.log(`wrote ${out} (${css.length} bytes)`);
  } else {
    console.log(css);
  }
}
