// ─── The app's token emitter ───
//
// Emits `apps/web/src/styles/tokens.css` from the ONE pigment source,
// `packages/shared/src/design-tokens.ts`.
//
// The attribute API is the browser's own three-state theme, not a custom one:
//
//   :root                                  the light system, always defined
//   @media (prefers-color-scheme: dark)     what "system" resolves to
//   :root[data-theme="dark"|"light"]        an explicit choice, which wins
//   [data-theme="dark"|"light"]             the same choice on any container,
//                                           which is how /gallery shows both
//                                           grounds in one document
//
// Every token has a value on bare `:root`. A colour whose only definition is
// inside a media query or an attribute block is a colour that is missing in one
// of the three states, and the state it is missing in is always the one nobody
// tested.
//
// `[data-accent]` survives with a single value on purpose. It is the hidden
// `[ui] accent` override a custom build still wants, and a seam that says "this
// was a choice, and the choice is one" is more honest than deleting it and
// pretending there was never a decision.
//
// Usage:  bun run scripts/generate-tokens-css.ts [outfile]

import { writeFileSync } from "fs";
import {
  GEAR_ACCENT_NAMES,
  GEAR_ACCENT_CSS,
  GEAR_BASE_CSS,
  GEAR_SCALE,
  GEAR_TYPE,
  type GearBaseName,
} from "../packages/shared/src/design-tokens";

const CSS_NAME: Record<keyof (typeof GEAR_BASE_CSS)["light"], string> = {
  ground: "--ground",
  surface: "--surface",
  sunk: "--sunk",
  raised: "--raised",
  ink: "--ink",
  ink2: "--ink-2",
  ink3: "--ink-3",
  inkFaint: "--ink-faint",
  hairline: "--hairline",
  hairlineStrong: "--hairline-strong",
  accent: "--accent",
  accentHover: "--accent-hover",
  onAccent: "--on-accent",
  ok: "--ok",
  caution: "--caution",
  danger: "--danger",
  shadowOverlay: "--shadow-overlay",
};

/**
 * The derived tints, as `color-mix` of a colour already in the system.
 *
 * Never a second hex. A "light blue" authored by hand is a second brand colour
 * arriving through the back door of a hover state; 8% of the accent over the
 * ground is the accent, quieter.
 */
function tints(base: GearBaseName): string[] {
  const css = GEAR_BASE_CSS[base];
  const fill = base === "dark" ? 14 : 8;
  const edge = base === "dark" ? 34 : 30;
  const statusFill = base === "dark" ? 16 : 10;
  return [
    `  --accent-quiet: color-mix(in srgb, ${css.accent} ${fill}%, transparent);`,
    `  --accent-edge: color-mix(in srgb, ${css.accent} ${edge}%, transparent);`,
    `  --ok-quiet: color-mix(in srgb, ${css.ok} ${statusFill}%, transparent);`,
    `  --caution-quiet: color-mix(in srgb, ${css.caution} ${statusFill}%, transparent);`,
    `  --danger-quiet: color-mix(in srgb, ${css.danger} ${statusFill}%, transparent);`,
    `  --danger-edge: color-mix(in srgb, ${css.danger} ${edge}%, transparent);`,
  ];
}

function groundRows(base: GearBaseName): string[] {
  const css = GEAR_BASE_CSS[base];
  const rows = (Object.keys(CSS_NAME) as Array<keyof typeof CSS_NAME>).map(
    (key) => `  ${CSS_NAME[key]}: ${css[key]};`,
  );
  return [`  color-scheme: ${base};`, ...rows, ...tints(base)];
}

export function renderTokensCss(): string {
  const scale = [
    `  --sans: ${GEAR_SCALE.sans};`,
    `  --mono: ${GEAR_SCALE.mono};`,
    "",
    `  --ease: ${GEAR_SCALE.ease};`,
    `  --t-fast: ${GEAR_SCALE.fast};`,
    `  --t-panel: ${GEAR_SCALE.panel};`,
    "",
    "  /* Three radii. A circle is a circle, not a corner. */",
    `  --r-chip: ${GEAR_SCALE.radiusChip};`,
    `  --r: ${GEAR_SCALE.radius};`,
    `  --r-composer: ${GEAR_SCALE.radiusComposer};`,
    "",
    `  --label-tracking: ${GEAR_SCALE.labelTracking};`,
    `  --title-tracking: ${GEAR_SCALE.titleTracking};`,
    `  --display-tracking: ${GEAR_SCALE.displayTracking};`,
    "",
    `  --sidebar-w: ${GEAR_SCALE.sidebarWidth};`,
    `  --sidebar-icons-w: ${GEAR_SCALE.sidebarIconsWidth};`,
    `  --rail-w: ${GEAR_SCALE.railWidth};`,
    `  --column-max: ${GEAR_SCALE.columnMax};`,
    `  --column-min: ${GEAR_SCALE.columnMin};`,
    "",
    "  /* The type scale, so a component asks for a step rather than a number. */",
    ...(Object.keys(GEAR_TYPE) as Array<keyof typeof GEAR_TYPE>).flatMap((step) => [
      `  --fs-${step}: ${GEAR_TYPE[step].size};`,
      `  --lh-${step}: ${GEAR_TYPE[step].line};`,
    ]),
  ];

  return [
    "/* Generated by scripts/generate-tokens-css.ts — DO NOT EDIT.",
    " * Source of truth: packages/shared/src/design-tokens.ts.",
    " * Two grounds, one accent, hairlines not shadows, radii from {6, 8, 10}. */",
    "",
    ":root {",
    ...scale,
    "",
    ...groundRows("light"),
    "}",
    "",
    "/* What the system setting resolves to. Guarded so an explicit light choice",
    "   still wins on a machine set to dark. */",
    "@media (prefers-color-scheme: dark) {",
    '  :root:not([data-theme="light"]) {',
    ...groundRows("dark").map((r) => `  ${r}`),
    "  }",
    "}",
    "",
    "/* An explicit choice, which wins in both directions. */",
    ':root[data-theme="dark"] {',
    ...groundRows("dark"),
    "}",
    "",
    "/* The same choice, scoped to a CONTAINER rather than the page.",
    "",
    "   Added for /gallery, which shows every primitive on both grounds side by",
    "   side and therefore needs two palettes alive in one document. It is a",
    "   generalisation rather than a special case: the three-state theme above is",
    "   the page's, and these two selectors say the same thing about any element",
    "   that declares a theme. Root matches both; the `:root`-qualified rules are",
    "   more specific and carry identical values, so nothing changes for a page",
    "   that never nests a theme. */",
    '[data-theme="light"] {',
    ...groundRows("light"),
    "}",
    "",
    '[data-theme="dark"] {',
    ...groundRows("dark"),
    "}",
    "",
    accentBlocks(),
    "",
  ].join("\n");
}

function accentBlocks(): string {
  const blocks: string[] = [];
  for (const accent of GEAR_ACCENT_NAMES) {
    const light = GEAR_ACCENT_CSS.light[accent];
    const dark = GEAR_ACCENT_CSS.dark[accent];
    blocks.push(`[data-accent="${accent}"] {\n  --accent: ${light};\n}`);
    blocks.push(
      `@media (prefers-color-scheme: dark) {\n` +
        `  :root:not([data-theme="light"])[data-accent="${accent}"] {\n` +
        `    --accent: ${dark};\n` +
        `  }\n}`,
    );
    blocks.push(`:root[data-theme="dark"][data-accent="${accent}"] {\n  --accent: ${dark};\n}`);
  }
  return blocks.join("\n\n");
}

/**
 * Format the emitted CSS the way the repository formats everything else.
 *
 * Not cosmetic: `format:check` runs over the whole tree, and a generated file
 * that prettier disagrees with turns "regenerate the tokens" into "regenerate
 * the tokens and then remember to format them", which is a step somebody will
 * forget on the one commit where it matters.
 */
async function formatted(css: string, filepath: string): Promise<string> {
  try {
    const prettier = (await import("prettier")) as {
      format: (source: string, opts: Record<string, unknown>) => Promise<string>;
      resolveConfig: (p: string) => Promise<Record<string, unknown> | null>;
    };
    const config = (await prettier.resolveConfig(filepath)) ?? {};
    return await prettier.format(css, { ...config, filepath });
  } catch {
    return css; // no prettier: the file is still correct, just unformatted
  }
}

if (import.meta.main) {
  const out = process.argv[2];
  const css = renderTokensCss();
  if (out) {
    const text = await formatted(css, out);
    writeFileSync(out, text);
    console.log(`wrote ${out} (${text.length} bytes)`);
  } else {
    console.log(css);
  }
}
